/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

package problem2

import "testing"

func TestSumOfEvenFibNumbersLessThan100(t *testing.T) {
	testSumOfEvenFib(t,100,44)
}

func testSumOfEvenFibNumbersLessThan4000000(t *testing.T) {
	testSumOfEvenFib(t,4000000,4613732)
}

func testSumOfEvenFib(t *testing.T, max, expected int) {
	actual := sumOfEvenFib(max)
	if actual != expected {
		t.Errorf("sumOfEvenFib(%v) = %v, want %v", max, actual, expected)
	}
}

