/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
package problem2

func sumOfEvenFib(max int) int {
	sum := 0
	p,c := 1,2
	for c < max {
		if p%2==0 {sum+=p}
		p,c = fib(p,c)
	}
	return sum
}

func fib(previous,current int) (int, int) {
	return current, previous + current
}

